name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    uses: andregoepel/workflows/.github/workflows/ci-hostapp.yml@main
    with:
      global-json-file: global.json
      restore-projects: |
        src/AndreGoepel.UrlShortener/AndreGoepel.UrlShortener.csproj
        tests/AndreGoepel.UrlShortener.Tests/AndreGoepel.UrlShortener.Tests.csproj
        tests/AndreGoepel.UrlShortener.IntegrationTests/AndreGoepel.UrlShortener.IntegrationTests.csproj
      apphost-project: src/AndreGoepel.UrlShortener.AppHost/AndreGoepel.UrlShortener.AppHost.csproj
      e2e-project: tests/AndreGoepel.UrlShortener.E2ETests/AndreGoepel.UrlShortener.E2ETests.csproj
      test-filter: "FullyQualifiedName!~E2ETests"
